### PR TITLE
route builder for compiler

### PR DESCRIPTION
**Pull request by Thingographist**
simple extensible

### CODE REVIEW

**Comment by Thingographist** [comment]
For example:

```clojure
(defrecord CompiledRoute [source re keys]
  clout.core/Route
  (route-matches [_ request]
    (let [path-info (:path request)
          matcher   (re-matcher re path-info)]
      (if (.matches matcher)
        (assoc-keys-with-groups (re-groups* matcher) keys))))
  Object
  (toString [_] source))
```

**Comment by weavejester** [comment]
Sorry, I still don't understand *why*. What are you trying to do? What problem does this solve?

**Comment by Thingographist** [comment]
My use-case https://github.com/Thingographist/zoo-routing/blob/master/src/zoo_routing/clout.clj .

**Comment by weavejester** [comment]
You've linked some code, but I really need an explanation of what you're trying to do, and what problem this PR will solve for you.

**Comment by Thingographist** [comment]
In current solution i cant use custom implementation of protocol "Route". This approach make its possible.

**Comment by weavejester** [comment]
You've explained *what* you want, but not *why* you want it. I need an explanation of what you're trying to do, and what problem this PR will solve for you.

**Comment by Thingographist** [comment]
I want use custom realization of route protocol for matching another keywords from another source-map.

**Comment by weavejester** [comment]
Why? What's the purpose?

**Comment by Thingographist** [comment]
Why exist another request map and resource? What explain this map?

**Comment by weavejester** [comment]
I'm afraid I don't understand what that means :(

I took a look at the README for your project. It looks like you're trying to use Clout for matching maps that are not Ring requests. If that is the case, then it's probably better you develop your own version than depend on Clout.

**Comment by Thingographist** [comment]
Thanks.

**Pull request closed without merging**
