### PR TITLE
Update Instaparse dependency

### PR DESCRIPTION
**Pull request by yurrriq**
Instaparse 1.3.6 throws a weird Exception on Clojure 1.7.0 beta 2. The problem is fixed in Instaparse 1.4.0. ([gist writeup][1])

**Note**: [Compojure's clout dependency][2] will need to be updated accordingly.

[1]: https://gist.github.com/yurrriq/4190ca1f404a5745e214
[2]: https://github.com/weavejester/compojure/blob/694225dc415f65a2a9bcc0316e411c611402db6a/project.clj#L8

### CODE REVIEW

**Comment by weavejester** [comment]
Could you update the 1.7 profile to beta2 as well, so we have some tests?

**Comment by yurrriq** [comment]
Should I bump the clout version for sanity as well?

**Comment by weavejester** [comment]
No, just the things related to the desired change.

**Comment by yurrriq** [comment]
:+1:

**Comment by weavejester** [comment]
Thanks. Could you update the commit summaries to be a little more descriptive. Something like:

    Update Instaparse to 1.4.0

    Fixes an issue with Clojure 1.7.0-beta2.

And:

    Update Clojure 1.7 test profile to 1.7.0-beta2

**Pull request merged**
