### PR TITLE
Fix bugs in ClojureScript version

### PR DESCRIPTION
**Pull request by xafizoff**
Fixed some bugs in ClojureScript implementation of clout

### CODE REVIEW

**Comment by xafizoff** [comment]
Hi, James. Can you consider this PR, please?

**Comment by weavejester** [comment]
Sure, I was just waiting for you to tell me that you were finished making changes.

Can you add a test for the `toString` method? It would be nice to ensure it works in ClojureScript to prevent regressions or errors. We can also add an equivalent Clojure test while we're at it.

Can you also remove all backticks from the commit messages? The commit messages of this repository are formatted as plain text, not markdown.

**Comment by xafizoff** [comment]
Done.

**Comment by xafizoff** [comment]
PS. In addition, I would implement `Route.route-matches` for `PersistentVector`. 
I.e.
```clojure
(route-matches ["/foo/:id" :id #"\d+"])
```
which is equivalent to
```clojure
(route-matches "/foo/:id" {:id #"\d+"})
```
I know that is possible with Compojure, which performs such transformations at compile time. But with ClojureScript compile-time and runtime environments are completely different. It is related to [that issue](https://stackoverflow.com/questions/18542956/can-anybody-explain-why-compojures-routing-macro-only-accepts-literal-vector-as)

**Comment by weavejester** [comment]
> PS. In addition, I would implement `Route.route-matches` for `PersistentVector`.

Sorry, I'm not sure I follow. Why not just write a function that turns a vector into a compiled route?

**Comment by weavejester** [comment]
Can you squash the `toString` commits together and remove the remainder of the backticks in the commit messages?

**Comment by xafizoff** [comment]
Done.

> Sorry, I'm not sure I follow. Why not just write a function that turns a vector into a compiled route?
Yeah, you're right.

**Comment by xafizoff** [comment]
Any updates?

**Comment by weavejester** [comment]
Ah, sorry, I missed your earlier post. Can you remove the body from the commit message? I think the subject line is fine. Then bug me again when you're done and I'll merge and release today.

**Comment by xafizoff** [comment]
Done.

**Comment by xafizoff** [comment]
Ping

**Comment by weavejester** [comment]
Released as 2.2.1.

**Comment by xafizoff** [comment]
Thank you.

**Pull request merged**
